<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibrarySystem.DAL\LibrarySystem.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Interfaces\" />
    <Folder Include="Services\Classes\" />
  </ItemGroup>

</Project>
